services:
  app:
    image: availe:latest
    platform: linux/arm64
    networks:
      - webnet
    pull_policy: never

  nginx:
    image: nginx:latest
    platform: linux/arm64
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/private:/etc/ssl/private:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
    depends_on:
      - app
    networks:
      - webnet
    pull_policy: never

networks:
  webnet:
