name: Deploy App

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
  workflow_dispatch:
    inputs:
      cache-bust:
        description: "Cache bust value to force cache invalidation"
        required: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}-${{ github.event.inputs.cache-bust || 'default' }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}-

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          tags: availe:latest
          outputs: type=docker
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Save Docker image
        run: |
          docker save availe:latest | gzip > availe.tar.gz

      - name: Transfer files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "availe.tar.gz, docker-compose.yml, nginx.conf"
          target: "${{ secrets.TARGET_PATH }}"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.TARGET_PATH }}
            docker-compose down
            docker load < availe.tar.gz
            docker-compose up -d

      - name: Clean up
        run: |
          rm availe.tar.gz
